### ISSUE TITLE
changing case unnecessary

### ISSUE THREAD

**Issue by jeremy-coleman** [DominicTobias/react-js2css-theme#1]
hi friend, i use something similar to this. just wanted to share the --variables are case sensitive , so you can actually just pass in the cssObject's keys as the variable names , so for example 
```
mytheme={
themePrimary: 'blue'
} 

:root {
--themePrimary: blue;
}

will work

**Comment by DominicTobias** [comment]
Ah that’s good to know thanks, I’ll make a next major version with that
approach instead at some point

**Comment by DominicTobias** [comment]
Updated in 2.0.0
